### ISSUE TITLE
Revive sometimes fails

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#1]
@AoiKagase The reviving action sometimes fail, and it does not complete the revival process

**Comment by AoiKagase** [comment]
The gauge will advance and complete, but it does not revive.
Is that what you're saying?

**Comment by eflernicolas** [comment]
> The gauge will advance and complete, but it does not revive. Is that what you're saying?

Exactly that, yes.

**Comment by AoiKagase** [comment]
There was indeed a processing route where nothing happened.
This is because Rivive is failing, so we fixed it so that the user is notified by chat message and sound.

**Comment by eflernicolas** [comment]
> There was indeed a processing route where nothing happened. This is because Rivive is failing, so we fixed it so that the user is notified by chat message and sound.

is revive failing a main functionality of the plugin? was not aware of that, any possibility to create a CVAR to disable that?

**Comment by AoiKagase** [comment]
No, this is an irregular pattern that cannot happen.
If an irregularity occurs for some reason, nothing happens and the system stops, so a message is notified.

One possible cause is that you were not revived in time or you moved out of the revive range.
