### ISSUE TITLE
Doubts about the plugin

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#10]
To understand the mechanic of reviving i have some questions regarding plugin behaviour.

1) it might be obvious but i will ask anyway, removing the revive task from bots with the cvar so they can no longer revive or be revived, will make the plugin lighter?

2) When a player spawns, the point where his crosshair  was pointing is conserved, lets say player A revives player B, but before dying player B was looking at the floor, after reviving player B will still be looking at the floor.

3) The respawn mechanic in humans and bots everytime does a little strange thing:
Steps to reproduce:

A) player or bot is killed
B) notice how his corpse falls to the ground, disappear and a second corpse appear  (revive corpse i assume) (normal behaviour till now)
but then, a third body appears on top of it, and the second body starts disappearing into the ground.
This present absolutely NO issue in the action of reviving, i just want to know if this is a potential bug or something that could make my fps drop with lots of friends in the sv

**Comment by eflernicolas** [comment]
> To understand the mechanic of reviving i have some questions regarding plugin behaviour.
> 
>     1. it might be obvious but i will ask anyway, removing the revive task from bots with the cvar so they can no longer revive or be revived, will make the plugin lighter?
> 
>     2. When a player spawns, the point where his crosshair  was pointing is conserved, lets say player A revives player B, but before dying player B was looking at the floor, after reviving player B will still be looking at the floor.
> 
>     3. The respawn mechanic in humans and bots everytime does a little strange thing:
>        Steps to reproduce:
> 
>     First:  player or bot is killed
> 
>     Second:. notice how his corpse falls to the ground, disappear and a second corpse (revive corpse i assume) appear (normal behaviour till now)
>        but then, a third body appears on top of it, and the second body starts disappearing into the ground.
>        This present absolutely NO issue in the action of reviving, i just want to know if this is a potential bug or something that could make my fps drop with lots of friends.

**Comment by AoiKagase** [comment]
1. I don't think there is much difference in this, but setting rkit_bot_can_revive 0 and rkit_bot_has_kit 0 will disable all processing for the bot.
See if that makes a difference.
2. I'll have to look into this.
3. The situation regarding B has not been confirmed.
