### ISSUE TITLE
Progress bar and Time not working

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#11]
No matter how much i set rkit_delay_revive to, revival is performed almost instantly, and there is no progress bar

**Comment by AoiKagase** [comment]
I’m currently investigating.

**Comment by eflernicolas** [comment]
thanks for the cvar of the obstacle thing. maybe adding it to the main page with the other cvars?

Should i test the #11 commit? since you closed it but then reopened it. this is the last bug , i hope. thanks for solving every error and maintaining this plugin :)

**Comment by AoiKagase** [comment]
I've been able to reproduce the phenomenon and identify the cause, which I've already fixed.
It would be helpful if you could test it as well.
Please close it when you can confirm.

**Comment by eflernicolas** [comment]
Can confirm that it works just fine!

last question, you think this is compatible with rehlds, regame or reapi?

**Comment by eflernicolas** [comment]
plugin works just fine

**Comment by AoiKagase** [comment]
> last question, you think this is compatible with rehlds, regame or reapi?

In my test environment, I am using RegameDLL.
ReAPI is not required, so there is no problem.
