### ISSUE TITLE
Keep revived player Aim to same camera angles you were before dying.

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#14]
For eg: you are looking at the sky, you get killed, then you get revived, you are looking at the sky again instead of default view back to center of screen , probably same as spawn origin.

this helps a lot to find your way when you suddenly get revived, and you get disoriented instead.

**Comment by AoiKagase** [comment]
In other words, you want to resurrect them with their gaze intact at the time of death?

**Comment by eflernicolas** [comment]
I think we mean the same thing, yes!

Basically resurrect with my crosshair aiming at the same place at the time of death.

**Comment by eflernicolas** [comment]
I tested the last commit and could not achieve the desired effect

**Comment by eflernicolas** [comment]
Thank you!!! seems to be working just fine!, is there anything you could do to optimize revival when corpses are sometimes between walls? i have been getting quite a few failed revives lately.  I am not checking for walls of course.

**Comment by AoiKagase** [comment]
>is there anything you could do to optimize revival when corpses are sometimes between walls? i have been getting quite a few failed revives lately. I am not checking for walls of course.

If `rkit_check_obstacle` is 0, try increasing the value of `rkit_distance` slightly.

To be technical, the detection of corpses involves the first one found and visible in EngFunc_FindEntityInSphere.
However, if rkit_check_obstacle is 0, whether it is visible or not will always be True, so the first corpse detected by EngFunc_FindEntityInSphere will be the target.
However, if the range of this Sphere is too small, detection itself may not be possible.
