### ISSUE TITLE
(Bug/limitation)Wider Check for revive spot

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#15]
After thorough testing:

Revive sometimes fail when corpse is too close to the wall or close to a tunnel, under a train, or closed corner. 
I think this happens because the plugin check for a narrow area for suitable spots. How about widening it a little bit? This may help reduce the numbers of failed revives.

Thanks for your time and effort

**Comment by AoiKagase** [comment]
Have you tried changing `rkit_distance`?

**Comment by eflernicolas** [comment]
Yes, of course.

The revive failing is not the same as not finding the target.
So revive distance is fine.

What is failing to complete is the revive action:

I like the radius of revive i have. I just want the game to try to respawn the player at a greater distance if obstructions are find. That is what happens in closed areas, corners, props near by,  corpse under brushed, etc.
Given the case that is the actual cause of failed reviving, of course.

**Comment by eflernicolas** [comment]
im happy with the result. could you elaborate on what the revive_attempt cvar does?

**Comment by eflernicolas** [comment]
walking without bots in a map got this server crash:

`L 06/23/2022 - 21:25:17: [AMXX] Displaying debug trace (plugin "custom_revival_kit_test.amxx", version "0.6")
L 06/23/2022 - 21:25:17: [AMXX] Run time error 10: native error (native "pev")
L 06/23/2022 - 21:25:17: [AMXX]    [0] custom_revival_kit_test.sma::find_dead_body (line 837)
L 06/23/2022 - 21:25:17: [AMXX]    [1] custom_revival_kit_test.sma::PlayerPostThink (line 503)
L 06/23/2022 - 21:25:17: [FAKEMETA] Invalid entity`

**Comment by AoiKagase** [comment]
> im happy with the result. could you elaborate on what the revive_attempt cvar does?

Randomly calculate a point in range 10.0 from before and check for obstructions 10 times.
If all of these failed, they were not revived.

In `rkit_revive_radius`, the range, `rkit_revive_attempt` specifies the number of times to check.

**Comment by eflernicolas** [comment]
thank you, seems to be working fine. will let you know if any other error happens.
