### ISSUE TITLE
(Request) Remove player maxspeed limitation.

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#16]
The original plugin you took over and made this awesome plugin made it possible so you could freely move while reviving.
Of course, there is a possibility bugs were caused by it.

If you think is possible, could you make it so the player does not has to stop moving while he is reviving another player?

What happens is:

Player reviving another player can move but  while pressing the revive button he will be lead to stop moving intermitently.

What i want:

Move without forcing to stop in a radius freely across the corpse while reviving it,  and as long as i dont break the revive radius everything will go as intended.

Thank you!

**Comment by AoiKagase** [comment]
I have found the logic to stop the movement while the E button is pressed.
Please wait a little longer as we have not been able to guarantee that it will work when moved out of range.

**Comment by eflernicolas** [comment]
> I have found the logic to stop the movement while the E button is pressed. Please wait a little longer as we have not been able to guarantee that it will work when moved out of range.

That is amazing! 

Remember it would be logic for the revive to fail when moved out of range.

as long as i can walk around the revival radius without stopping should be enough for me :)

**Comment by eflernicolas** [comment]
Working flawlessly. thank you!
