### ISSUE TITLE
New Bug - Corpses stay over to the next rounds

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#18]
Some corpses stay over all rounds until the end of map. currently only seen CT bots corpses. since i am testing the plugin without human players for now.

Map i noticed this happening is in cs_estate

**Comment by AoiKagase** [comment]
At cs_estate, I tested with `rkit_delay_die` 1 and the corpse disappeared immediately.

**Comment by eflernicolas** [comment]
> At cs_estate, I tested with `rkit_delay_die` 1 and the corpse disappeared immediately.

It happened once, but never ever before and only updated the revival kit plugin so i guess it is related.

The bots have disabled the revive for them. It is available only for humans.

It happened once, they died and next round they still were there.

I assume it will happen again.  Sometime.

As i said it never happened before it seems strange that it just happened when i decide to update the revive kit to the radius fix version

**Comment by eflernicolas** [comment]
Maybe was a one time bug, it can happen sometime. Closing this for now since. It is not easily reproducible. I just wanted to let you know so the plugin does not go out of hand and later we will not know what changes changed what.
