### ISSUE TITLE
Error -  Cvar without effect

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#19]
e_cvar RKIT_RESPAWN_DROP does not meet  g_CVarString rkit_respawn_weaponstrip"

**Comment by AoiKagase** [comment]
The process is being handled at the time of revive, but the timing of the process is too fast and It may not be functioning.
(This may be one of the reasons why set_task is used so much, as it is in other issues.)

**Comment by eflernicolas** [comment]
what i meant with this request is that the cvar of stripping weapons but allowing to pickup the ones nearby, is not working, probably because the cvar is defined in those two different ways.

i changed the rkit_respawn_weaponstrip cvarstring to rkit_respawn_drop and when activated, human/bots respawn with nothing, not even a knife. 
would be wise to add only the knife, otherwise is glitchy and complicated to carry on

**Comment by AoiKagase** [comment]
If rkit_respawn_weaponstrip 0, the previous weapon is recovered.
If 1, Knife only.

**Comment by eflernicolas** [comment]
thank you

using it with 1 is problematic because items are lost in time, would be nice to spawn player without the secondary weapon and grab the ones on the floor. but adding the strip weapon function is problematic.

Not important, if you find a way around it, let me know, closing this issue ! :)
