### ISSUE TITLE
After Reviving, 1 out of 10 times aprox, the user cannot switch his weapon and lose his crosshair.

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#2]
the bug occurs when reviving a teammate, and sometimes the revived player cannot change to secondary weapon or knife, and is stuck with its primary weapon and not being able to see the crosshair

**Comment by AoiKagase** [comment]
Am I correct in assuming that when player [A] revives player [B], player [A] will have a problem?

**Comment by eflernicolas** [comment]
> Am I correct in assuming that when player [A] revives player [B], player [A] will have a problem?

Incorrect

Player (A) revives player (B) , player (B) after reviving,  is missing the crosshair and cannot switch to other weapons.

Player(A) never have problems.

I wonder if a respawn plugin  like this one : https://forums.alliedmods.net/showthread.php?t=105241 

combined with this one https://forums.alliedmods.net/showthread.php?p=2375211

would this be easier method for reviving or maybe put you in the right direction?:

Lets say you use the "spawn at last place" plugin way of detecting last position of death, keep the corpse at that position, then use "revive a teammate plugin" but make it only detect nearby players, (so you dont revive globally and lose immersion) and maybe use the letter E to do it, and avoid all the revive kits part.

I have noticed the revive a temmate plugin never bugs even if you revive a player thousand of times.

**Comment by AoiKagase** [comment]
This cannot be tested by one person.
Something may have changed due to the modification of the revive process.

**Comment by eflernicolas** [comment]
> This cannot be tested by one person. Something may have changed due to the modification of the revive process.

Indeed is hard to test since you need to be revived for it to be investigated and later fixed. Sadly this is the worst of all the bugs!

**Comment by AoiKagase** [comment]
Yes, it would take more than two players to check this, which makes it difficult for me to check.
However, unlike the previous resuscitation process, it now works more like a normal Respawn process, so it may be an improvement.

**Comment by AoiKagase** [comment]
I tried to test the revival process by reviving myself using the Self Revive function.
I tested it for about an hour and it seems to be working fine.

**Comment by eflernicolas** [comment]
> I tried to test the revival process by reviving myself using the Self Revive function. I tested it for about an hour and it seems to be working fine.

thats amazing will be testing it today, since i know that bug happened like 1 out ot 10 times

**Comment by eflernicolas** [comment]
Tested this too and its working flawlessly.
