### ISSUE TITLE
[Question] Values lower than 1.0 in CVAR rkit_delay_revive makes progress bar disappear 

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#20]
Probably hardcode limit but, can you force it to work with lower values?

**Comment by AoiKagase** [comment]
Since the time Cheap_Suit created it, each process has been delayed by heavy use of set_task.
Perhaps one of these is affecting it and needs to be investigated.
Worst case, it may be necessary to extensively rework the part of the process that is being handled by the set_task.

**Comment by AoiKagase** [comment]
This is probably a Counter-Strike specification, since the number of seconds that can be specified for the progress bar to appear can only be set to an integer.

**Comment by eflernicolas** [comment]
Great ! good to know. closing it then
