### ISSUE TITLE
[Request] Shorter Fake Corpse Spawn time

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#21]
When a player dies, takes a few seconds to the "fake corpse" to appear slowing down the revival process a little bit.
Is it currently at the max speed for it to spawn or can you make it faster?

**Comment by AoiKagase** [comment]
This has been around since Cheap_Suit created it, but it is set at 0.5 seconds to create a corpse after death.
I will investigate and try to adjust it, but I think there is some reason for this and it may be an unexpected glitch.

**Comment by eflernicolas** [comment]
is it too crazy to reconsider simplyfying the plugin by an extreme margin?

just an idea:

What if instead of the whole corpses thing a sprite would appear at the spot of death. like in this plugin:

Link to Plugin(Sourcemod):
https://forums.alliedmods.net/showthread.php?p=2629611

Example Image:
https://i.ytimg.com/vi/N5UcJk5wZQs/maxresdefault.jpg


Would that make the revive process faster, and cleaner? also the plugin lighter maybe?

I think also this would make the spot of actual death the same as revive instead of waiting for a corpse to fall down lets say, died and flew away with a grenade, hit the spot, then fake corpse appears instead of that, make the sprite appear at the exact spot of death and revive by pressing e on the sprite.

**Comment by AoiKagase** [comment]
Please check to see if the behavior has changed in response to #22.

**Comment by eflernicolas** [comment]
it is indeed faster! thanks! but regarding that fix,  a bug you can reproduce:

Join pool day or emir (if you have it) since they spectator cameras are on T  spawns, if you join a team, but don't select  a terrorist skin. a CT ghost spawns . don't know what this would suppose to be in terms of code. but if i disable revival kit it doesnt appear.

**Comment by eflernicolas** [comment]
error fixed! thanks!
