### ISSUE TITLE
Weapon Strip Error

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#3]
After a player is revived if he had a weapon or c4 on the ground nearby the corpse, the weapons will be stripped and disappear from map.

**Comment by AoiKagase** [comment]
The relevant part is strip_user_weapons, but we need to investigate how it works when it is used on a deceased person.

**Comment by eflernicolas** [comment]
> The relevant part is strip_user_weapons, but we need to investigate how it works when it is used on a deceased person.

Removing strip user weapons from your code fixes the problem, but i supposed it was there for a reason. Not stripping the weapons is a good way of just picking up what you dropped on death

**Comment by AoiKagase** [comment]
Removed strip_user_weapon.
