### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#5]
First of all thanks for all the time you put into this. for context, this plugin is top tier in my sv with friends adds infinite possibilities.

Would it be possible to add the following functions to the plugin?

- CVAR for enabling/disabling bots ability to buy revivalkit
- CVAR for disabling bots functionality and restrict revive only to human players.
- CVAR for buying outside of buyzone.
- CVAR/function for already spawning with a revival kit, without the need to buy one.

**Comment by AoiKagase** [comment]
> * CVAR for enabling/disabling bots ability to buy revivalkit
Add `rkit_bot_has_kit`
> * CVAR for disabling bots functionality and restrict revive only to human players.
Add `rkit_bot_can_revive`
> * CVAR for buying outside of buyzone.
Add `rkit_buy_zone`
> * CVAR/function for already spawning with a revival kit, without the need to buy one.
Add `rkit_buy_mode`

**Comment by AoiKagase** [comment]
Please close the issue when you have confirmed that it is complete. (The same applies to other issues.)

**Comment by eflernicolas** [comment]
> Please close the issue when you have confirmed that it is complete. (The same applies to other issues.)

tested first to see that everything worked :)
