### ISSUE TITLE
Reviving a player is done while Pressing E Key bug

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#6]
While reviving Player B and Player A walking at the same time  around the corpse range distance of revival, it lags the movement speed of player A for the remaining time of the revival bar to be completed.

**Comment by AoiKagase** [comment]
Does this mean that if two people try to revive the same person, they will be revived twice?

**Comment by eflernicolas** [comment]
> Does this mean that if two people try to revive the same person, they will be revived twice?

not at all. what i meant is that if  I , player A, try to revive player B, my movement speed is affected, 
In early versions of the original plugin i am almost 100% percent this did not happen

**Comment by AoiKagase** [comment]
As I understand it, there is no process that can affect the speed of others.

There is one place where pressing EKey immediately sets the speed of the player who pressed it to zero, but I don't think it affects other players.
Also, it would take more than two players to check this, which makes it difficult for me to check.

**Comment by eflernicolas** [comment]
> 

actually this also happens when reviving bots, its a tricky thing to do move while you press E, and sometimes it may seem quite a bit unnecessary but i did it, and the bug happened.

**Comment by AoiKagase** [comment]
If the rescue icon is flashing while you hold down the E key, your movement speed will be reduced to zero in order to catch the corpse.
