### ISSUE TITLE
Cvars not working properly

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#9]
I just restarted my server from scratch to apply the cvars i configured in amxx.cfg:

//custom_revivalkit.amxx

rkit_health 100
rkit_cost 0
rkit_screen_fade 0
rkit_screen_fade_time 0
rkit_delay_revive 1
rkit_delay_die 0
rkit_distance 200.0
rkit_bot_has_kit 0
rkit_bot_can_revive 1
rkit_buy_mode 0
rkit_buy_zone 0
rkit_deathmatch 0

Using changelevel did not work, so i had to restart the server from scratch

Worked 1 time, then i shutted down the server for another test, and all the cvars are now the default from plugin,
what i mean is all the cvars i just stated above  are not working anymore , those configurations are invalid

What is weird is that in console if i check the cvars, they are these same values, but only default values from code  seems to be applying
For example: i set my rkit_cost to 0 , i check the cvar in console and it is effectively 0.
I try to buy a revive, it says you dont have enough money, you need $1200

Also i have buy mode 0 , but i still have to buy after spawning,  basically, they are not applying

**Comment by AoiKagase** [comment]
It needs to be investigated.
Please let me know the result of the command "amxx version","meta version".
and operating system.

**Comment by AoiKagase** [comment]
It fixes the Cvar process and displays debug messages on the console.
7a661cd

**Comment by eflernicolas** [comment]
> It fixes the Cvar process and displays debug messages on the console. [7a661cd](https://github.com/AoiKagase/Amxx-ReviveKit/commit/7a661cdb2c0c9a5897b88baa2c3225f0adc27195)

The strangest thing happens, if change the cvar, for example rkit_buy_mode from 1 to 0, it takes TWO changelevels for it to apply, or a complete server restart, other than that values apply.

**Comment by AoiKagase** [comment]
Did you see a log on the Console when the changes were made?
And what version of AMXX are you using?

**Comment by eflernicolas** [comment]
i am using 1.9  build 5294

**Comment by AoiKagase** [comment]
please report this command output.
```meta version
meta list
amxx version
amxx plugins
status

**Comment by eflernicolas** [comment]
Sorry about the delay! here it is :

Meta:

```
Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.9.0.5  ini  Start ANY
 [ 2] Engine           RUN   -    engine_amxx.dll   v1.9.0.5  pl1  ANY   ANY
 [ 3] FakeMeta         RUN   -    fakemeta_amxx.dl  v1.9.0.5  pl1  ANY   ANY
 [ 4] CStrike          RUN   -    cstrike_amxx.dll  v1.9.0.5  pl1  ANY   ANY
 [ 5] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.9.0.5  pl1  ANY   ANY
 [ 6] CSX              RUN   -    csx_amxx.dll      v1.9.0.5  pl1  ANY   ANY
 [ 7] Fun              RUN   -    fun_amxx.dll      v1.9.0.5  pl1  ANY   ANY
7 plugins, 7 running

```

AMXX Version:
```
amxx version
AMX Mod X 1.9.0.5294 (http://www.amxmodx.org)
Authors:
        David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
        Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
        Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
        Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Dec  3 2021 22:52:28
Built from: https://github.com/alliedmodders/amxmodx/commit/363871a8
Build ID: 5294:363871a8
Core mode: JIT+ASM32

```

Amxx plugins:
```

amxx plugins
Currently loaded plugins:
       name                    version     author            file             status
 [  1] Admin Base              1.9.0.5294  AMXX Dev Team     admin.amxx       running
 [  2] Admin Commands          1.8.2       AMXX Dev Team     admincmd.amxx    running
 [  3] Maps Menu               1.9.0.5294  AMXX Dev Team     mapsmenu.amxx    running
 [  4] NextMap                 1.9.0.5294  AMXX Dev Team     nextmap.amxx     running
 [  5] TimeLeft                1.9.0.5294  AMXX Dev Team     timeleft.amxx    running
 [  6] check whitelist         1.0         bugsy             custom_whitelis  running
 [  7] Map Spawns Editor       1.0.16      iG_os             custom_Map_Spaw  running
 [  8] Buyzone Range           0.1         VEN               custom_buyzoner  running
 [  9] Team Money              1.0         Cheap_Suit        custom_teammone  running
 [ 10] No Use Through Walls    1.1         Numb              custom_nousethr  running
 [ 11] Weapons MaxSpeed        0.0.5       ConnorMcLeod      custom_weapons_  running
 [ 12] Ultimate Fire in the H  2.1         OciXCrom          custom_crx_fire  running
 [ 13] He damage Multiplier    1.2         Nightscream       custom_he-multi  running
 [ 14] Bomb Plant Money Bonus  1.0         Locks             custom_amx_plan  running
 [ 15] Style C4 Timer          3.1         OciXCrom          custom_crx_c4ti  running
 [ 16] Plant Anywhere          0.2         KRoTaL            custom_plant_an  running
 [ 17] Defuse Mistake          1.4         Redshift187       custom_dfmistak  running
 [ 18] Extra Damage Mod        0.2         v3x               custom_extradam  running
 [ 19] Show Players            1.0         NapoleoN#         custom_playerst  running
 [ 20] Automatic Unstuck       1.5         NL)Ramon(NL       custom_stuck.am  running
 [ 21] Disable startup MOTD    1.0         Sn!ff3r           custom_disable_  running
 [ 22] Allow round finish      1.0.2       EKS               custom_allow_ro  running
 [ 23] Simple Menu             2.1.2       OciXCrom          custom_crx_simp  running
 [ 24] Info Message HUD        1.3         Blizzard/guipati  custom_InfoMsg.  running
 [ 25] Auto Heal & Spawn Heal  0.1.5       ConnorMcLeod      custom_autoheal  running
 [ 26] Map Generator           1.2         Suicid3           custom_map_gene  running
 [ 27] Revival Kit / Remaster  0.1         Aoi.Kagase        custom_revival_  running
27 plugins, 27 running


```

Status:

```

status
hostname:  Condition Zero
version :  48/1.0.0.3 8684 secure  (80)
tcp/ip  :  192.168.0.53:27015
map     :  de_dust2 at: 0 x, 0 y, 0 z
players :  0 active (32 max)

#      name userid uniqueid frag time ping loss adr
0 users

```

**Comment by AoiKagase** [comment]
Are you sure it's ConditionZero and not CS1.6?
And is it Listen Server instead of HLDS?

**Comment by AoiKagase** [comment]
Try modify your plugin.ini to load the plugin first.
Also, the file name is given a custom_, have you changed any code?

**Comment by eflernicolas** [comment]
> Are you sure it's ConditionZero and not CS1.6? And is it Listen Server instead of HLDS?

Absolutely sure its condition zero, its a Dedicated Server using steamcmd,

**Comment by eflernicolas** [comment]
> Try modify your plugin.ini to load the plugin first. Also, the file name is given a custom_, have you changed any code?

No, i have not changed any code since i am not a dev. 

The reason "custom_" exists is to easily manage native amxx plugins with custom plugins i download, its for my  on file  organization sake.

There is absolutely no code changed

**Comment by eflernicolas** [comment]
> Try modify your plugin.ini to load the plugin first. Also, the file name is given a custom_, have you changed any code?

I will try to modify the load order, this should fix cvar not applying right?

Have you seen the progress bar and "fixed" delay reviving issue? thats part of core of the plugin and it is not working :)

**Comment by AoiKagase** [comment]
>I will try to modify the load order, this should fix cvar not applying right?

No, that is part of the investigation into the cause, and there is no guarantee that it will work correctly.

**Comment by eflernicolas** [comment]
> > I will try to modify the load order, this should fix cvar not applying right?
> 
> No, that is part of the investigation into the cause, and there is no guarantee that it will work correctly.

Now its working fine. thanks!
